### PR TITLE
Add the repo dir to safe config if used directly

### PR DESCRIPTION
**Pull request by jeanconn**
## Description
Add the repo dir to safe config if used directly. 

## Interface impacts
Updates the user's gitconfig and throws a UserWarning if code is called that uses a chandra_models repo that is not owned by the user.

### Unit tests

- [x] Mac (tested at d805180)

Independent check of unit tests by @taldcroft
- [x] Linux (see https://github.com/sot/ska_helpers/pull/37#issuecomment-1630988347)

### Functional tests

I configured my chandra_models repo to again be owned by not-me, pytest ran the drift model test out of chandra_aca, and confirmed the UserWarning and the chandra_models repo added to the safe directory of my .gitconfig.  I suppose we need an additional functional test that this works correctly if the model version is specified.

Also @taldcroft, see https://github.com/sot/ska_helpers/pull/37#issuecomment-1630988347.

### CODE REVIEW

**Comment by jeanconn** [comment]
Not sure what you had in mind @taldcroft but I took a crack at it.

**Comment by taldcroft** [comment]
On linux (HEAD) with no special env vars set I'm seeing this test failure:
```
ska_helpers/git_helpers.py:37: FileNotFoundError
============================================= short test summary info =============================================
FAILED ska_helpers/tests/test_chandra_models.py::test_get_model_file_fail - FileNotFoundError: '__NOT_A_DIRECTORY__' is not the top level of a git repo
```
This also needs a rebase, so I'm not sure if that problem will go away. I get a clean run of tests on current master.

**Comment by taldcroft** [comment]
The GitHub tool to resolve the merge conflict seems to have worked.

**Comment by jeanconn** [comment]
Regarding the test fail... Huh.  Fails for me now too though I thought they ran with no errors when I checked that box in the description.  If you want to implement differently with that in mind that's fine @taldcroft .  Otherwise I'll see if I can figure out whatever I missed here.

**Comment by taldcroft** [comment]
I just pushed a fix. Doing the `git.Repo(repo_dir)` is always "safe", but that will fail in the expected way if `repo_dir` doesn't exist.

**Comment by taldcroft** [comment]
And I confirmed the functionality of this PR on HEAD linux:
```
# Edit ~/.gitconfig to remove the [safe] directory

$ pytest ska_helpers 
...
================================================ warnings summary =================================================
ska_helpers/tests/test_chandra_models.py::test_get_data_extra_kwargs
  /data/baffin/tom/git/ska_helpers/ska_helpers/chandra_models.py:95: UserWarning: Updating git config to allow read-only git operations on trusted repository /proj/sot/ska3/flight/data/chandra_models. Contact Ska team for questions.
    make_git_repo_safe(repo_path)

$ pytest ska_helpers
...
NO WARNINGS

# Confirm that the .gitconfig [safe] section is updated as expected
[safe]
	directory = /proj/sot/ska/data/chandra_models
```

**Review by taldcroft — APPROVED** [review]
Looks good!

**Pull request merged**
